# Generated by Django 3.1.7 on 2021-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('INT', 'Intel'), ('AMD', 'AMD')], max_length=3)),
                ('line', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('year', models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('core_count', models.SmallIntegerField()),
                ('thread_count', models.SmallIntegerField()),
                ('consumption', models.SmallIntegerField()),
                ('base_freq', models.FloatField()),
                ('turbo_freq', models.FloatField()),
                ('ram_type', models.CharField(max_length=9)),
                ('ram_channels', models.SmallIntegerField()),
                ('pcie_rev', models.SmallIntegerField()),
                ('pcie_lanes', models.SmallIntegerField()),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
