# Generated by Django 3.1.7 on 2021-04-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ext_ip', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('OFF', 'Disconnected'), ('WOR', 'Working'), ('MAN', 'Maintenance')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NVIDIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('RTX', 'GeForce RTX'), ('QUA', 'Quadro'), ('GTX', 'GeForce GTX'), ('QTX', 'Quadro RTX'), ('DCT', 'DataCenter Line')], max_length=3)),
                ('model', models.CharField(max_length=10)),
                ('year', models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('vram', models.SmallIntegerField()),
                ('core_count', models.SmallIntegerField()),
                ('teraflops', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.machine')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.nvidia')),
            ],
        ),
    ]
